### ISSUE TITLE
Support for Leading, Trailing etc

### ISSUE THREAD

**Issue by madhikarma** [ustwo/autolayout-helper-swift#10]
There are some attributes not support by the helper as Leading, Trailing etc 

I'm not 100% sure but this may be an issue if the new right to left language support is for those layout attributes specifically 

https://developer.apple.com/library/ios/documentation/MacOSX/Conceptual/BPInternational/SupportingRight-To-LeftLanguages/SupportingRight-To-LeftLanguages.html

To resolve we could add new methods such as `addLeadingConstraint` or `addTrailingConstraint`
and advise to use those for labels instead of `addLeftConstraint` or `addRightConstraint`

We should also see how the new support works 

cc @danieladias @jamaine-ustwo @chris59david

**Comment by martinstolz** [comment]
👍 on this one.
